/**
 * jxa-plugin.js
 *
 * webpack plugin that adds a shebang and some JS code at the beginning and a run function at the end of the
 * code generated by webpack so that it can be run as a JXA script from the OS X command line.
 *
 * @author <a href="mailto:pahund@team.mobile.de">Patrick Hund</a>
 * @since 28 Nov 2015
 */
var ConcatSource = require("webpack-core/lib/ConcatSource");

function JxaPlugin() {
    this.banner =
        "#!/usr/bin/env osascript -l JavaScript\n" +
        "ObjC.import(\"stdlib\");\n" +
        "ObjC.import(\"AppKit\");\n" +
        "window = this;\n";
    this.footer =
        "function run(args) { this.main(args); }";
}

JxaPlugin.prototype.apply = function(compiler) {
    var banner = this.banner;
    var footer = this.footer;
    compiler.plugin("compilation", function(compilation) {
        compilation.plugin("optimize-chunk-assets", function(chunks, callback) {
            chunks.forEach(function(chunk) {
                chunk.files.forEach(function(file, i) {
                    compilation.assets[file] = new ConcatSource(banner, "\n\n", compilation.assets[file], "\n\n", footer);
                });
            });
            callback();
        });
    });
};

module.exports = JxaPlugin;
